# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./SampleProject

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Build unit tests image
      run: docker build -f UnitTests/Dockerfile -t dotnet-tests .
    - name: Run unit tests
      run: |
        mkdir -p test-results
        docker run --rm -v ${{ github.workspace }}/test-results:/app/TestResults dotnet-tests
    - name: Store test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/TestResults.trx
    - name: Prettify test report
      uses: dorny/test-reporter@v1
      with:
        name: Unit Tests
        path: test-results/TestResults.trx
        reporter: dotnet-trx
