# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: SampleProject PR

on:
  push:
    branches: [ "main" ]
    paths:
      - 'SampleProject/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'SampleProject/**'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./SampleProject

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: topSecretUser
          POSTGRES_PASSWORD: topSecretPassword
          POSTGRES_DB: topSecretDb
        options: >-
          --health-cmd="pg_isready -U topSecretUser -d topSecretDb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Build unit tests image
      run: docker build -f UnitTests/Dockerfile -t dotnet-tests .
    - name: Run unit tests
      run: docker run --rm dotnet-tests
    - name: Run integration tests
      run: dotnet test IntegrationTests/IntegrationTests.csproj
